---
title: "data preparation"
author: "wenyu"
date: "3/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
# NCATS dataset https://matrix.ncats.nih.gov/ "Malaria TACT" project all 3-agent combinations
# Download files
setwd("C:/Users/wenyu/Documents/work group Jing/Drugcomb/synergyfinder/synergyfinderplus_showcase")
dir <-"C:/Users/wenyu/Documents/work group Jing/Drugcomb/synergyfinder/synergyfinderplus_showcase" 
url.base <- "https://tripod.nih.gov/matrix-client/rest/matrix/export/%s?default"

# change following line with the adday IDs on NCATA Matrix webpage
id <- 12255
url <- sprintf(url.base, id)
file.name <- paste0(as.character(id), ".zip")
download.file(url = url, destfile = paste0(dir, "/data/raw_data/", file.name), mode = "wb")
unzip(paste0(dir, "/data/raw_data/", file.name), exdir = paste0(dir, "/data/unzip/", id))
calc <- read.csv(paste0("./data/unzip/", id, "/calc.csv"), stringsAsFactors = FALSE)
meta <- read.csv(paste0("./data/unzip/", id, "/metadata.csv"), stringsAsFactors = FALSE)
response <- read_csv(file = paste0("./data/unzip/", id, "/responses.csv")) %>% 
  select(-Layer) %>% 
  mutate(Replicate= str_split(Replicate,pattern = "default",n = 2,simplify = T)[,1]) %>% 
  mutate(Replicate= as.integer(Replicate))


# Change following line with the concentrations for 3rd drug (available on webpage)
# meta$Conc3 <- c(
#   0.75, 0.375, 0.1875, 0.938, 0.469, 0.0234, 0.0117, 0.0059,
#   0.0029, 0.0015, 0.0007, 0
# )
conc3 <- unique(unlist(str_split(meta$RowConcs,pattern = ",",n = 12)))
meta <- meta %>% mutate(Conc3= conc3)

# Change following line with the 3rd drug's name and length 
meta$Drug3 <- rep("Piperaquine", length(meta$Conc3))

data <- NULL

for (i in 1:nrow(meta)) {
  Conc1 <- as.numeric(unlist(strsplit(meta$RowConcs[i], ",")))
  Conc2 <- as.numeric(unlist(strsplit(meta$ColConcs[i], ",")))
  tmp <- response[which(response$BlockId == i), ]
  # Change "1" in the following line for different assays/blocks
  df <- data.frame(block_id = rep(1, nrow(tmp)), stringsAsFactors = FALSE)
  df$drug1 <- rep(meta$RowName[i], nrow(df))
  df$drug2 <- rep(meta$ColName[i], nrow(df))
  df$drug3 <- rep(meta$Drug3[i], nrow(df))
  df$donc1 <- rep(Conc1, each = 10)
  df$donc2 <- rep(Conc2, times = 10)
  df$donc3 <- rep(meta$Conc3[i], nrow(df))
  df$response <- tmp$Value
  df$conc_unit1 <- rep(meta$RowConcUnit[i], nrow(df))
  df$conc_unit2 <- rep(meta$ColConcUnit[i], nrow(df))
  df$conc_unit3 <- rep("uM", nrow(df))
  data <- rbind.data.frame(data, df)
}

# Run codes above on all the assays and merge all tables together.

```


```{r}
library(rvest)
# library(rebus)
thirddrug_info <- read_html("https://matrix.ncats.nih.gov/matrix-client/rest/matrix/blocks/12255/table") 

tmp <- thirddrug_info %>% 
  html_nodes(".idcell") %>%
  html_text()
idx <- seq.int(from = 3,to = length(tmp),by = 3)
tmp1 <- tmp[idx]

tmp2 <- str_split(string = as.matrix(tmp1),pattern = "uM", n=2,simplify =T)

tmp3 <- as_tibble(data.frame(tmp2)) %>% 
  mutate(id= 1:length(idx)) %>% 
  mutate(X3= str_detect(X1, "\\("))


tmp4 <- tmp3 %>% 
  filter(X1== "DMSOUnknown") %>% 
  mutate(drug3= "DMSO") %>% 
  mutate(conc3= 0) %>% 
  select(id, drug3, conc3)


# conc_pattern <- 
#   START %R% 
#   " " %R% 
#   or((one_or_more(DGT) %R% "." %R% one_or_more(DGT)), one_or_more(DGT) )  %R%
#   END
# # 
# str_detect("a 51", conc_pattern)
# str_extract("a 5.1", conc_pattern)



tmp5 <- tmp3 %>% filter(!X3) %>% 
  filter(X1 != "DMSOUnknown") %>%
  mutate(X4= str_split(X1, pattern = " ")) %>%
  mutate(drug3= map_chr(.x = X4,
                        .f = function(x) {
                          x1= unlist(x)
                          tmp <- str_c(x1[ -length(x1):-(length(x1)-1)],collapse = " ")
                          return(tmp)
                          } )) %>%
  mutate(conc3= map_chr(.x = X4,
                        .f = function(x) {
                          x1= unlist(x)
                          tmp <- x1[ length(x1)-1]
                          return(tmp)
                          } )) %>%
  select(id, drug3, conc3) %>% 
  mutate_at(.vars = 3,.funs = as.numeric)

  

tmp6 <- tmp3 %>% 
  filter(X3) %>% 
  mutate(X4= str_split(X1, pattern = "\\) ")) %>% 
  mutate(drug3= map_chr(.x = X4,.f = function(x) {
    tmp <- x[[1]]
    tmp1 <- paste0(tmp,  ")")
    return(tmp1)
    } )) %>% 
  mutate(conc3= map_dbl(.x = X4,.f = function(x) {
    tmp <- as.numeric(x[[2]])
    return(tmp)
    } ))  %>% 
  select(id, drug3, conc3)

id <- rep(1:10, each = nrow(response)/10)
complete <- bind_rows(tmp4, tmp5, tmp6) %>% 
  mutate(conc_unit3= "uM") %>% 
  arrange(id) %>% 
  bind_cols(calc %>% select(BlockId,	Replicate)) %>% 
  inner_join(meta,by = "BlockId") %>% 
  select(-id) %>% 
  distinct() %>% 
  separate_rows(RowConcs,sep = ",") %>% 
  separate_rows(ColConcs,sep= ",") %>% 
  rename( drug1= RowName) %>% 
  rename(drug2=ColName) %>% 
  rename(conc1= RowConcs) %>% 
  rename(conc2= ColConcs) %>% 
  rename(conc_unit1= RowConcUnit) %>% 
  rename(conc_unit2= ColConcUnit) %>% 
  arrange(conc1,decreasing=T) %>% 
  mutate(Row= id) %>% 
  arrange(conc2,decreasing=T) %>% 
  mutate(Col= id) %>% 
  left_join(response) %>%
  mutate(conc1= as.numeric(conc1)) %>% 
  mutate(conc2= as.numeric(conc2)) %>%  
  select(BlockId,Replicate,drug1,drug2,drug3,conc1,conc2,conc3,conc_unit1,conc_unit2,conc_unit3,  RowSid, ColSid)


# now deal with the DMSO issue, basically use response of rows where third drug is DMSO as zero concentration response for all the other drug 3

DMSO <- complete %>% filter(drug3 == "DMSO")

other_drug3 <- complete %>% filter(drug3 != "DMSO") %>% pull(drug3) %>% unique()

complete_enhanced <- DMSO %>% 
  mutate(drug3= str_c(other_drug3,collapse = ",")) %>% 
  separate_rows(drug3,sep = ",") %>% 
  bind_rows(complete %>% filter(drug3 != "DMSO")) %>% 
  distinct() 


```



lets try wrap it into the function
```{r}



```



```{r}
data <- get_triocomb_data(id = 12255) 
data1 <- data %>% 
  # mutate_at(6:8, .funs = function(x){x*1000}) 
  filter(block_id==1) %>% 
  # filter(drug3== "Atazanavir") %>% 
  # filter(Replicate== 1)

library(synergyfinder)
res <- ReshapeData(data1, data_type = "inhibition")

# Plot monotherapy dose-response curves and dose response matrix
PlotDoseResponse(res, statistic = "ci", block_ids = 1,save_file = T,width = 30,height = 15)
Plot2DrugSurface(res, plot_block = 1)

# Calculate and visualize synergy scores
res_hsa <- CalculateSynergy(res, method = c("HSA"))
res_Bliss <- CalculateSynergy(res, method = c("Bliss"))
res_loewe <- CalculateSynergy(res, method = c("Loewe"))
res_zip <- CalculateSynergy(res, method = c("ZIP"))

# 2D heatmap with 95% confidence intervals
Plot2DrugHeatmap(res_hsa,plot_value = "HSA_synergy", plot_block = 1, statistic = "ci") 
Plot2DrugHeatmap(res_Bliss,plot_value = "Bliss_synergy", plot_block = 1, statistic = "ci")  
# 2D heatmap with 95% confidence intervals and mean hsa synergy for whole matrix
Plot2DrugHeatmap(res_loewe, plot_value = "Loewe_synergy", plot_block = 1,
                 statistic = "ci", summary_statistic = "mean")
Plot2DrugHeatmap(res_zip, plot_value = "ZIP_synergy", plot_block = 1,
                 statistic = "ci", summary_statistic = "mean")
# 3D landscape
Plot2DrugSurface(res_hsa, plot_value = "HSA_synergy", plot_block = 1)
Plot2DrugSurface(res_zip, plot_value = "ZIP_synergy", plot_block = 1)


```
```{r}
library(synergyfinder)
data <- get_triocomb_data(id = 11345) 
data1 <- data %>% 
  filter(block_id==3) %>% 
  filter(Replicate==1)
res_response = ReshapeData(data1, data_type = "viability")
res_hsa <- CalculateSynergy(res_response, method = c("HSA"))
res_Bliss <- CalculateSynergy(res_response, method = c("Bliss"))
res_loewe <- CalculateSynergy(res_response, method = c("Loewe"))
res_zip <- CalculateSynergy(res_response, method = c("ZIP"))


PlotMultiDrugSurface(res_response, plot_block = 3, plot_value = "response")
PlotMultiDrugSurface(res_hsa, plot_block = 3, plot_value = "HSA_synergy") # four synerg score
PlotMultiDrugSurface(res_Bliss, plot_block = 3, plot_value = "Bliss_synergy")
PlotMultiDrugSurface(res_loewe, plot_block = 3, plot_value = "Loewe_synergy")
PlotMultiDrugSurface(res_zip, plot_block = 3, plot_value = "ZIP_synergy")
```


synergistic example
```{r}
library(synergyfinder)
data <- get_triocomb_data(id = 12255) 
data1 <- data %>% 
  filter(block_id==8) %>% 
  filter(Replicate== 1)
  
res_response = ReshapeData(data1, data_type = "viability")
res_hsa <- CalculateSynergy(res_response, method = c("HSA"))
res_Bliss <- CalculateSynergy(res_response, method = c("Bliss"))
# res_loewe <- CalculateSynergy(res_response, method = c("Loewe"))
# res_zip <- CalculateSynergy(res_response, method = c("ZIP"))
PlotMultiDrugSurface(res_response, plot_block = 8, plot_value = "response")
PlotMultiDrugSurface(res_hsa, plot_block = 8, plot_value = "HSA_synergy") # four synerg score
PlotMultiDrugSurface(res_Bliss, plot_block = 8, plot_value = "Bliss_synergy")
# PlotMultiDrugSurface(res_loewe, plot_block = 8, plot_value = "Loewe_synergy")
# PlotMultiDrugSurface(res_zip, plot_block = 8, plot_value = "ZIP_synergy")
```


search for drugs 
```{r}
library(synergyfinder)

id_list= c(10023, 11345, 11911, 12254, 12255)

id_list1= 10736:10745

metatable <- read_csv("C:/Users/wenyu/Documents/work group Jing/Drugcomb/synergyfinder/synergyfinderplus_showcase/data/assay/metatable.csv")
id_list2 <- metatable %>% filter(comb==3) %>% pull(id)
res_summary2 <- 
  map(.x = id_list2,
      .f = function(x){
        dir <-"C:/Users/wenyu/Documents/work group Jing/Drugcomb/synergyfinder/synergyfinderplus_showcase" 
        trio_set_file_name <-  paste0(dir,"/data/trio_data/", x, ".csv")
        
        if (paste0(x, ".csv") %in% list.files(paste0(dir,"/data/trio_data/"))){
          data1 = read_csv(trio_set_file_name)
        } else {
          data1 <- get_triocomb_data(id = x) 
          write_csv(data1 , file = trio_set_file_name )
        }
        
        res_response = ReshapeData(data1, data_type = "viability")
        res_hsa <- CalculateSynergy(res_response , method = c("HSA"))
        res_Bliss <- CalculateSynergy(res_response , method = c("Bliss"))
        hsa_summary <- res_hsa$synergy_scores %>% 
          select(block_id, HSA_synergy) %>% 
          group_by(block_id) %>% 
          summarize(median= median(HSA_synergy) ,
                      mean= mean(HSA_synergy), 
                    max= max(HSA_synergy)
                      )
        bliss_summary <- res_Bliss$synergy_scores %>% 
          select(block_id, Bliss_synergy) %>% 
          group_by(block_id) %>% 
          summarize(median= median(Bliss_synergy) ,
                    mean= mean(Bliss_synergy), 
                    max= max(Bliss_synergy)
          )
        res <- c(hsa=list(hsa_summary), bliss=list(bliss_summary))
        return(res)
        } 
      )
```

