---
title: "R Notebook"
output: html_notebook
---

```{r}
library(openxlsx)
library(tidyverse)
```


```{r}
#note that the orignial data from oneil only contains so-called viability and ratio
# the viability in the oringial dataset is cell_after/cell_before
# the ratio in the original dataset isThe single-agent drug effects,
#expressed as fractional inhibition between 0 (maximal inhibition) and 1 (no inhibition) 
#relative to DMSO-treated controls
#so although there should be a readout for DMSO, it was not directly provided in the orginaldata
#but only record for drug.
#however with ratio value as well as the viability value for the drug provided in original 
#dataset we can recompute one viability value for DMSO for each cell*each batch

#actually using ratio value produce  weird value to via dmso


#another notice is that all the wells having a starting number of 400 cells


#

data5 <- read.xlsx('C:/Users/wenyu/Documents/work group Jing/Drugcomb/2016_ONeil/single.xlsx',1,na.strings = "NULL")
head(data5)
#calculating the median viability of DMSO
#we didn't figure out why this didn't work
# myfun1 <- function(x){
#   y= unlist(na.omit(x))
#   z= length(y)
#   y1=y[z]
#   y2=y[-z]
#   m=log(median(y1)) / (log(y2)/log(4) +1)
#   n= exp(m)
# }

#instead using mu/mumax to compute the via_dmso
myfun2 <- function(x){
  y= as.numeric(na.omit(x))
  z= length(y)
  y1=y[-z]
  y2=y[z]
  m=log(median(y1)) / (96*(y2-1))
  n= exp(m)
}


data_dmso= data.matrix(data5[, c(5:11)], rownames.force = NA)
data_dmso=apply(data_dmso, 1, myfun2 )
names(data_dmso)=NULL
#########
## check why there are Inf in computed dmso viability
#the Inf and the NA of via_DMSO is due to that the value mum/mumax equals 1
#which means the viability of drug treated cell equals to dmso treated cell
#in this case I can directly using the median of the drug treated cell viability
#to denote the viability for DMSO
# data5[which(data_dmso== Inf),]
# which(data_dmso== Inf)
# data5[is.na(data_dmso),]
# which(is.na(data_dmso))
# data5[c(3005,16417,11387),]
# via_dmso= data_dmso[c(-3005,-16417,-11387)]
# sort(x = via_dmso,decreasing = T)[1:10]
for (i in c(3005,16417,11387)){
   d= median(as.numeric(data5[i,5:10]),na.rm = T)
   names(d)=NULL
   data_dmso[i]= d
}
data_dmso[c(3005,16417,11387)]
data5$viadmso= data_dmso
# tbl_df(data5) %>% group_by(cell_line) %>% summarise(check= mean(viadmso))
# #check if the viadmso clustered to the cells
# library(ggplot2)
# p <-ggplot(data5, aes(x=as.factor(BatchID), y=viadmso))+
#   geom_boxplot()
# p
# 
# p <-ggplot(data5, aes(x=as.factor(cell_line), y=viadmso))+
#   geom_boxplot()+
#   theme(axis.text.x = element_text(size = 10,angle = 90, hjust = 1))
# p
# 
# data5$BatchID <- as.factor(data5$BatchID)
# tbl_df(data5) %>% filter(cell_line== "NCIH2122") %>% group_by(BatchID) %>% summarize(ave=mean(viadmso)) 
# hist((tbl_df(data5) %>% filter(cell_line== "NCIH2122") )$viadmso)
# check <- data <- tbl_df(data5) %>% filter(cell_line== "NCIH2122") %>% filter(viadmso> 1.022)
# fix(check)
# 
# hist((tbl_df(data5) %>% filter(cell_line== "COLO320DM") )$viadmso)
# check <- data <- tbl_df(data5) %>% filter(cell_line== "COLO320DM") %>% filter(viadmso>1.025)
# fix(check)
# 
# ##now I suspect that batch 1 and 2 used same control
# #while batch three used different control
# #another question is how can viability for cell so small
# table(filter(tbl_df(data5),BatchID==3) %>% select(cell_line))
# #despite it seems that this is the case in general, there are still some outlier
# #which we can't explain.

# we decide to neglect the outlier and use the median value of the estimated 
# dmso viability for each cell* batch
# 

data_dmso_1=select(tbl_df(data5), c(BatchID, cell_line, viadmso)) %>% 
  group_by(BatchID, cell_line) %>% 
  summarise(viability=median(viadmso))
data_dmso_1=mutate(data_dmso_1, drug_name='DMSO',conc=0,rep=1,cell_before=NA,cell_after=NA,time=96,resource='Oneil')
#now reformat the orignial wide matrix(with six replicate per row) to long
#matrix (six rows for the siz replicates within one batch for certain drug*cell*concentraion)
#the problem here is that there are only three replicates for some batch rather than six
#hence this result in some NA rows in the long_format of the data
#these NA rows can simply be deleted without influencing the others
colnames(data5)[5:10] <- 1:6
data5=data5[,c(-13:-11)]
library(tidyr)
colnames(data5)
data5= tbl_df(data5) %>% gather(key=rep, value= viability, -BatchID,-cell_line,-drug_name,-conc)
data5=mutate(data5,cell_before=NA,cell_after=NA,time=96,resource='Oneil')

###
#combine the data5 and dmso dataset
data5$rep=as.numeric(data5$rep)
data5=full_join(data5,data_dmso_1)
data5=data5[-which(is.na(data5$viability)),]
colnames(data5)[1] <- "batch"
data5$cell_after <- data5$cell_before <- as.numeric(data5$cell_before)
```


```{r}

comb2 <- read.xlsx('C:/Users/wenyu/Documents/work group Jing/Drugcomb/2016_ONeil/double.xlsx',1,na.strings = "NULL")
# data_dmso2=apply(comb2[, 7:11], 1, function(x) exp(log(median(x[-5], na.rm=TRUE)) / (x[5] - 1)))
# data_dmso2=data.frame(data_dmso2,comb2$batch,comb2$cell_line) 
# data_dmso2=tbl_df(data_dmso2) %>% filter(data_dmso2!=Inf) %>% filter(!is.na(data_dmso2))
# data_dmso2=data_dmso2 %>% group_by(comb2.batch,comb2.cell_line) %>% summarise(viability=median(data_dmso2))
#since comb data in Oneil is still using dmso from single drug experiments, we don't not add it here again
colnames(comb2)[7:10]=1:4
# comb2= comb2 %>% select(-ratio)
comb2= comb2 %>% gather(key=rep, value= viability, -batch,-cell_line,-drug1,-conc1,-conc2,-drug2)
comb2=mutate(comb2,cell_before=NA,cell_after=NA,time=96,resource='Oneil')
#colnames(comb2)[c(1:7)] <- c(colnames(comb1)[c(10,7,1,5,4,6,9)])
comb2$rep=as.integer(comb2$rep)
comb2= comb2[which(is.na(comb2$viability)==F),]

# how many blocks?
comb2 %>% select(drug1,drug2)  %>% distinct() %>% nrow()


comb2
```
Note to prepare drug combinnation screening data for synergy calculation, Single drug must be combined with doublue drug, so that synergy score can be calculated.

Jing ask me to use drugcomb curated data directly. I got a huge csv file from Jehad. Lets see how this works
```{r}
drugcomb_oneil <- read_csv("C:/Users/wenyu/Documents/work group Jing/Drugcomb/2016_ONeil/drugcomb_oneil.csv") 

data2 <- drugcomb_oneil %>% 
  filter(block_id==1) %>% 
  filter(cell_line_name== "A2058") %>% 
  mutate(ConcUnit= "uM")

library(synergyfinder)
res2 <- ReshapeData(data2, data_type = "inhibition")
  

# Plot monotherapy dose-response curves and dose response matrix
PlotDoseResponse(res2, statistic = "ci", block_ids = 1,save_file = T,width = 30,height = 15)
Plot2DrugSurface(res2, plot_block = 1)

# Calculate and visualize synergy scores
res_hsa <- CalculateSynergy(res2, method = c("HSA"))
res_Bliss <- CalculateSynergy(res2, method = c("Bliss"))
res_loewe <- CalculateSynergy(res2, method = c("Loewe"))
res_zip <- CalculateSynergy(res2, method = c("ZIP"))
```

